pipeline:
  name: JavaSecCode
  identifier: JavaSecCode
  projectIdentifier: magman
  orgIdentifier: sandbox
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: ONGAMSE
        repoName: pc-javaseccode-GH
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: small
              imageSpec:
                imageName: ubuntu-latest
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven
                  identifier: Maven
                  spec:
                    shell: Sh
                    command: mvn compile package
              - stepGroup:
                  name: Harness SAST-SCA
                  identifier: Harness_SASTSCA
                  steps:
                    - parallel:
                        - step:
                            type: HarnessSAST
                            name: Harness Code
                            identifier: Harness_Code
                            spec:
                              mode: orchestration
                              config: sast_sca
                              target:
                                type: repository
                                detection: auto
                              advanced:
                                log:
                                  level: debug
                                args:
                                  cli: "--container 18fgsa/s3-resource"
                            enforce:
                              policySets:
                                - Fail_on_Reachable_Findings
                        - step:
                            type: HarnessSCA
                            name: Harness Container
                            identifier: Harness_Container
                            spec:
                              mode: orchestration
                              config: default
                              target:
                                type: container
                                detection: auto
                              advanced:
                                log:
                                  level: debug
                              privileged: true
                              image:
                                type: docker_v2
                                tag: latest
                                name: 18fgsa/s3-resource
                            enforce:
                              policySets:
                                - Fail_on_High_EPSS
                          contextType: Pipeline
              - stepGroup:
                  name: Supply Chain
                  identifier: Supply_Chain
                  steps:
                    - step:
                        type: SscaOrchestration
                        name: SBOM Generation
                        identifier: SBOM_Generation
                        spec:
                          mode: generation
                          tool:
                            type: Syft
                            spec:
                              format: spdx-json
                          source:
                            type: repository
                            spec:
                              url: https://github.com/ongamse/pc-javaseccode-GH
                              variant_type: branch
                              variant: master
                          sbom_drift:
                            base: repository
                            spec:
                              variant: master
                          resources:
                            limits:
                              memory: 500Mi
                              cpu: "0.5"
                    - step:
                        type: provenance
                        name: SLSA Generation_1
                        identifier: SLSAGeneration_1
                        spec:
                          source:
                            type: har
                            spec:
                              registry: org.sandbox
                              image: hello-seccode
                          attestation:
                            type: keyless
                            spec:
                              oidcProvider: harness
                      contextType: Pipeline
